# Generated by Django 3.1.6 on 2021-02-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=15)),
                ('vin', models.CharField(blank=True, max_length=30, unique=True)),
                ('mileage', models.PositiveIntegerField()),
            ],
        ),
    ]
