# Generated by Django 3.1.6 on 2021-03-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploaded_images/'),
        ),
    ]
