# Generated by Django 3.1.6 on 2021-03-14 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20210306_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_time',
            new_name='modified_date_time',
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
