# Generated by Django 3.1.6 on 2021-03-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20210313_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='inspected_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='insured_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_inspected',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_insured',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_registered',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='registered_exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
