# Generated by Django 3.1.6 on 2021-03-22 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20210313_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_on_date', models.DateField()),
                ('owner', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.car')),
            ],
        ),
    ]
