# Generated by Django 3.1.6 on 2021-03-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
