# Generated by Django 3.1.6 on 2021-03-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20210322_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
