# Generated by Django 3.1.6 on 2021-03-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20210322_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='update_mileage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
