# Generated by Django 3.1.6 on 2021-04-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20210406_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/entry_images/'),
        ),
    ]
