# Generated by Django 3.1.6 on 2021-04-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_auto_20210406_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='img',
            new_name='image2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='fyle',
        ),
        migrations.AddField(
            model_name='entry',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='media/entry_images/'),
        ),
    ]
